server:
  port: 8207

spring:
  application:
    name: service-task
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.123.130
                port: 5672
                username: root
                password: 123321
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名称
          destination: exchange.direct.task # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置

